version: '3.8'
services:
  mysqldb:
    image: mysql:5.6
    container_name: "mysql-db"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: amazing_toy
      MYSQL_ROOT_PASSWORD: ProjectSEM4@2020
      SERVICE_NAME: mysql
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    links:
      - mysqldb
    container_name: AmazingToy-Service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local